USPS_CLIENT_ID = "PIG7lOPiCNEt6h7Akrgm7NAQIeiZKWtHp6lpqVro7Bxn3B9j"
USPS_CLIENT_SECRET = "oR9z6fIdfuLx7QxPHSsNa7KAEVtBluvVDKB9D9s9edkqO9X47vx3XR9UfLOh5A75"

# Streamlit App Configuration
[theme]
primaryColor = "#3b82f6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#1e293b"

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false